version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - epub
  - htmlzip

build:
  apt_packages:
    - "graphviz"
  image: latest
  python:
    version: 3.12
  jobs:
    post_checkout:
      - git fetch --unshallow
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/pdf/
      - python -m sphinx -T -E -b latex -d docs/_build/doctrees -D language=en docs docs/build/
      - cd docs/build/ && cat latexmkrc
      - cd docs/build/ && latexmk -r latexmkrc -pdf -f -dvi- -ps- -jobname=pybamm -interaction=nonstopmode || true
      - test -f docs/build/pybamm.pdf && echo "pybamm.pdf exists. Copying source file to $READTHEDOCS_OUTPUT/pdf/."
      - cp "docs/build/pybamm.pdf" $READTHEDOCS_OUTPUT/pdf/

python:
  install:
    - method: pip
      path: .
